IMG_ATTR_DOUBLE = {
    "IMG_ATTR_BLACK_REF_VOLT",
    "IMG_ATTR_COLOR_BRIGHTNESS",
    "IMG_ATTR_COLOR_CHROMA_PHASE",
    "IMG_ATTR_COLOR_CONTRAST",
    "IMG_ATTR_COLOR_GAIN_BLUE",
    "IMG_ATTR_COLOR_GAIN_GREEN",
    "IMG_ATTR_COLOR_GAIN_RED",
    "IMG_ATTR_COLOR_HIGH_REF_VOLT",
    "IMG_ATTR_COLOR_HUE_OFFS_ANGLE",
    "IMG_ATTR_COLOR_LOW_REF_VOLT",
    "IMG_ATTR_COLOR_NTSC_SETUP_VALUE",
    "IMG_ATTR_COLOR_SW_POST_GAIN"
    "IMG_ATTR_COLOR_SATURATION",
    "IMG_ATTR_COLOR_TINT",
    "IMG_ATTR_WHITE_REF_VOLT",
}

IMG_ATTR_UINT64 = {
    "IMG_ATTR_ENCODER_POSITION",
    "IMG_ATTR_POCL_STATUS"
}

IMG_ATTR_NA = {
    "IMG_ATTR_DATALINES",
    "IMG_ATTR_SERIAL_TERM_STRING"
}